"""Complete LNAV words, independent integer parity encoding (IS-GPS-200N 20-XIV)."""
import unittest
import contextlib
import io
import numpy as np
from gps import prn_gen
from gps.gps_receiver import FrameDecoder, Subframe3, Subframe, gps_parity, TrackingChannel, GpsReceiver
from test_navigation_fields import set_field


def encode_word(data, previous=0):
    masks = [0x3B1F3480, 0x1D8F9A40, 0x2EC7CD00,
             0x1763E680, 0x2BB1F340, 0x0B7A89C0]
    raw = data << 6
    seeds = [previous >> 1, previous & 1, previous >> 1,
             previous & 1, previous & 1, previous >> 1]
    parity = 0
    for mask, seed in zip(masks, seeds):
        parity = (parity << 1) | ((raw & mask).bit_count() % 2 ^ seed)
    return (raw ^ (0x3FFFFFC0 if previous & 1 else 0)) | parity


def frame_bits(frame_id=3, tow=12345):
    data = [0x8B0000, (tow << 7) | (frame_id << 2),
            0x123456, 0xABCDEF, 0xFFFE81, 0x234567,
            0x765432, 0xFEDCBA, 0x654321, 0x120000]
    words = []
    previous = 0
    for i, value in enumerate(data):
        if i in (1, 9):
            value &= ~3
            value = next(value | low for low in range(4)
                         if encode_word(value | low, previous) & 3 == 0)
        word = encode_word(value, previous)
        words.append(word)
        previous = word & 3
    return np.array([int(b) for w in words for b in f'{w:030b}'])


def feed(decoder, symbols, offset=0):
    result = []
    for i, sample in enumerate(symbols):
        frame = decoder.process(sample, 100.25 + (offset + i) * 4092)
        if frame is not None:result.append(frame)
    return result


class FrameDecoderTests(unittest.TestCase):
    def test_encoder_matches_independent_c_reference(self):
        # Generated by gps-sdr-sim computeChecksum at c31d15784688fe82fbfe8b146ed606f382101dd0.
        # These fixed transmitted words also pin the word-2/10 parity tails.
        expected = [int(x, 16) for x in '''22c00012 060723ec 048d1581 150c8430
            3fffa072 08d159c0 1d950c8b 0048d17b 26af37b2 0480007c'''.split()]
        bits = frame_bits()
        actual = [int(''.join(map(str, bits[i:i+30])), 2) for i in range(0, 300, 30)]
        self.assertEqual(actual, expected)

    def test_parity_all_previous_states_and_every_single_bit_error(self):
        for previous in range(4):
            for data in [0, 0xFFFFFF, 0x8B1234, 0xFEDCBA]:
                word = np.array([2 * int(b) - 1 for b in f'{encode_word(data, previous):030b}'])
                last = [2 * (previous >> 1) - 1, 2 * (previous & 1) - 1]
                self.assertEqual(gps_parity(word, last), -last[1])
                for bit in range(30):
                    bad = word.copy();bad[bit] *= -1
                    self.assertEqual(gps_parity(bad, last), 0)

    def test_complete_frame_returned_on_last_sample_both_polarities(self):
        for polarity in [1, -1]:
            decoder = FrameDecoder();decoder.reset(7)
            frames = feed(decoder, np.repeat(frame_bits() * 2 - 1, 20) * polarity)
            self.assertEqual(len(frames), 1)
            self.assertIsInstance(frames[0], Subframe3)
            self.assertEqual(frames[0].sv, 7)
            self.assertEqual(frames[0].tow, 12345 * 6 - 6)
            self.assertEqual(frames[0].position, 100.25)

    def test_corrupt_frame_rejected_then_next_frame_recovers(self):
        bits = frame_bits();bits[200] ^= 1
        symbols = np.repeat(np.concatenate([bits, frame_bits(2, 12346)]) * 2 - 1, 20)
        frames = feed(FrameDecoder(), symbols)
        self.assertEqual([f.id for f in frames], [2])
        self.assertEqual(frames[0].position, 100.25 + 6000 * 4092)

    def test_buffer_bounded_with_noise_and_repeated_frames(self):
        decoder = FrameDecoder()
        rng = np.random.default_rng(20260914)
        noise = rng.choice([-1, 1], 20000)
        self.assertEqual(feed(decoder, noise), [])
        self.assertLessEqual(len(decoder.sample_buffer), 6000)
        self.assertLessEqual(len(decoder.sample_positions), 6000)
        symbols = np.repeat(np.tile(frame_bits(), 5) * 2 - 1, 20)
        frames = feed(decoder, symbols, offset=len(noise))
        self.assertEqual(len(frames), 5)
        self.assertEqual(frames[0].position, 100.25 + len(noise) * 4092)
        self.assertLessEqual(len(decoder.sample_buffer), 6000)

    def test_cis_does_not_include_adjacent_inclination_bits(self):
        for raw in [-32768, -1, 0, 32767]:
            for adjacent in [0, 0x81, 0xFF]:
                words = ['0' * 30 for _ in range(10)]
                set_field(words, 5, 1, 16, raw)
                set_field(words, 5, 17, 24, adjacent)
                self.assertEqual(Subframe3(words, 0, 1).c_is, raw * 2**-29)

    def test_tow_wraps_at_week_boundary(self):
        words = ['0' * 30 for _ in range(10)]
        self.assertEqual(Subframe(words, 0, 1).tow, 604794)

    def test_tracking_blank_interval_does_not_join_separated_frame_pieces(self):
        ch = TrackingChannel(4092000, (25, .707, .25), (1, .707, 1))
        ch.start(7, 0, 0)
        symbols = np.repeat(frame_bits() * 2 - 1, 20)
        feed(ch.decoder, symbols[:3000])
        ch.update(np.zeros(4092 * 3, dtype=np.complex64))
        self.assertEqual(feed(ch.decoder, symbols[3000:], offset=3010), [])

    def test_dump_frames_returns_chronological_order_and_drains(self):
        rx = GpsReceiver(4092000, channels=2)
        words = ['0' * 30 for _ in range(10)]
        rx.channels[0].frames = [Subframe(words, 10, 1), Subframe(words, 30, 1)]
        rx.channels[1].frames = [Subframe(words, 20, 2)]
        self.assertEqual([f.position for f in rx.dump_frames()], [10, 20, 30])
        self.assertEqual(rx.dump_frames(), [])

    def test_public_receiver_acquires_tracks_and_decodes_three_subframes(self):
        fs = 4092000
        # Stream 20 ms chunks: no full recording allocation and no decoder injection.
        # Warmup lets the loops settle before the complete LNAV subframes begin.
        bits = np.concatenate([np.ones(5, dtype=int),
            *(frame_bits(i, 12344 + i) for i in [1, 2, 3]), np.ones(1, dtype=int)])
        cases = [(0, 0, 1), (37, fs / 4096, -1), (4090, -fs / 4096, 1)]
        for phase, frequency, polarity in cases:
            code = prn_gen.sample(1, fs, fs // 50, offset_samples=phase)
            with self.subTest(phase=phase, frequency=frequency, polarity=polarity), contextlib.redirect_stdout(io.StringIO()):
                rx = GpsReceiver(fs, channels=1)
                for i in range(len(bits)):
                    n = np.arange(fs // 50) + i * (fs // 50)
                    # Navigation bit edges follow the shifted C/A epoch.
                    nav = bits[np.minimum((n + phase) // (fs // 50), len(bits) - 1)] * 2 - 1
                    rx.process(code * nav * polarity * np.exp(2j * np.pi * frequency * n / fs))
                frames = rx.dump_frames()
                self.assertEqual(rx.acquired.tolist(), [1])
                self.assertEqual([f.id for f in frames], [1, 2, 3])
                self.assertEqual([f.tow for f in frames], [74064, 74070, 74076])
                for i, frame in enumerate(frames):
                    self.assertLess(abs(frame.position - (fs * (.1 + 6 * i) - phase)), 5)
                self.assertEqual(frames[2].c_is, -2 * 2**-29)
                self.assertLessEqual(len(rx.channels[0].decoder.sample_buffer), 6000)


if __name__ == '__main__':unittest.main()
